import re

HEADING_REGEX = r"^[^\n]+\n={2,}"
HEADING_PATTERN = re.compile(HEADING_REGEX)

SUB_HEADING_REGEX = r"^[^\n]+\n-{2,}"
SUB_HEADING_PATTERN = re.compile(SUB_HEADING_REGEX)

SUB_SUB_HEADING_REGEX = r"^(?:(\#+) .+ \1)"
SUB_SUB_HEADING_PATTERN = re.compile(SUB_SUB_HEADING_REGEX)

ORDERED_LIST_REGEX = r"^(?:\d\..+(?:\n|$))+"
ORDERED_LIST_PATTERN = re.compile(ORDERED_LIST_REGEX)

UNORDERED_LIST_REGEX = r"^(?:(?:\*|\-) .+(?:\n|$))+"
UNORDERED_LIST_PATTERN = re.compile(UNORDERED_LIST_REGEX)

BOLD_TEXT_REGEX = r"^\*\*.+\*\*"
BOLD_TEXT_PATTERN = re.compile(BOLD_TEXT_REGEX)

ITALIC_TEXT_REGEX = r"\*[^\*]+\*"
ITALIC_TEXT_PATTERN = re.compile(ITALIC_TEXT_REGEX)

STRIKETHROUGH_TEXT_REGEX = r"\-\-.+\-\-"
STRIKETHROUGH_TEXT_PATTERN = re.compile(STRIKETHROUGH_TEXT_REGEX)

UNDERLINE_TEXT_REGEX = r"\_.+\_"
UNDERLINE_TEXT_PATTERN = re.compile(UNDERLINE_TEXT_REGEX)

QUOTE_TEXT_REGEX = r"\`\`.+\'\'"
QUOTE_TEXT_PATTERN = re.compile(QUOTE_TEXT_REGEX)

LINK_TEXT_REGEX = r"\[.+?\]\(.+?\)"
LINK_TEXT_PATTERN = re.compile(LINK_TEXT_REGEX)
